# Generated by Django 3.0.1 on 2020-07-12 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('AccountName', models.CharField(max_length=20)),
                ('TransctionType', models.CharField(max_length=50)),
                ('Particulars', models.CharField(max_length=20)),
                ('Amount', models.IntegerField()),
            ],
        ),
    ]
