# Generated by Django 3.0.1 on 2020-07-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='RegIMO',
            field=models.CharField(default='', max_length=10),
        ),
    ]
