# Generated by Django 3.0.1 on 2020-07-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_payments_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='Micellaneous',
            field=models.IntegerField(default=0),
        ),
    ]
