# Generated by Django 3.0.1 on 2020-07-25 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addshg', '0002_loanregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('OpeningBalance', models.IntegerField()),
                ('LoanRepayment', models.IntegerField()),
                ('Interest', models.IntegerField()),
                ('ClosingBalance', models.IntegerField()),
                ('RegIMO', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
