# Generated by Django 3.0.1 on 2020-07-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addshg', '0004_shg_balanceamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shg',
            name='phno',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
